### ISSUE TITLE
Can you also support touchscreen?

### ISSUE THREAD

**Issue by Adithr123** [lospec/pixel-editor#66] opened 2021-12-09 00:56 UTC
Is there any way that Lospec Pixel Editor could support touchscreen? I use a Chromebook, and its a lot easier.

**Comment by skeddles** [comment] 2021-12-09 01:21
we do plan on adding touch support for mobile devices, hopefully soon (but no promises 😁)
(closing as dupe of #10)

**Closed by skeddles** 2021-12-09 01:21 UTC
